### ISSUE TITLE
Can't be used with lein

### ISSUE THREAD

**Issue by chrismurrph** [dm3/stopwatch#2]
Not in Clojars so have to use `git clone`. But then after that I cannot simply `lein install` as there's no `project.clj` file. So perhaps I need to use some maven command... Would be good if there was more documentation around getting to use this library even if boot doesn't happen to be your build tool.

**Comment by dm3** [comment]
Hi, 

are you sure you've specified the dependency as described in the [Usage](https://github.com/dm3/stopwatch#usage) section? 

It's definitely on the [Clojars](https://clojars.org/dm3/stopwatch) :)

EDIT: it's not supposed to work with Lein. It works with [Boot](http://boot-clj.com/) instead. Would be great if you could help with documentation as I won't have the time to troubleshoot this project with Lein.

**Comment by chrismurrph** [comment]
Yes I followed as per Usage. One reason I assumed not on Clojars is because you can't click through to Clojars to verify. Most libraries have this. I did my own thing in the end.
